name: planet
channels:
  - defaults
dependencies:
  - asn1crypto=1.2.0=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2019.11.27=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37hb5b8e2f_0
  - cfitsio=3.470=hb33e7b4_2
  - chardet=3.0.4=py37_1003
  - cryptography=2.8=py37ha12b0ac_0
  - curl=7.67.0=ha441bb4_0
  - expat=2.2.6=h0a44026_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - freexl=1.0.5=h1de35cc_0
  - gdal=3.0.2=py37hbe65578_0
  - geos=3.8.0=h0a44026_0
  - geotiff=1.5.1=h0b0f252_0
  - gettext=0.19.8.1=h15daf44_3
  - giflib=5.1.4=h1de35cc_1
  - glib=2.63.1=hd977a24_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.4=hfa1e0ec_0
  - icu=58.2=h4b95b61_1
  - idna=2.8=py37_0
  - intel-openmp=2019.4=233
  - jpeg=9b=he5867d9_2
  - json-c=0.13.1=h3efe00b_0
  - kealib=1.4.7=hf5ed860_6
  - krb5=1.16.4=hddcf347_0
  - libboost=1.67.0=hebc422b_4
  - libcurl=7.67.0=h051b688_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libdap4=3.19.1=h3d3e54a_0
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgdal=3.0.2=h42cfeda_0
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libkml=1.3.0=hbe12b63_4
  - libnetcdf=4.6.1=hd5207e6_2
  - libpng=1.6.37=ha441bb4_0
  - libpq=11.2=h051b688_0
  - libspatialite=4.3.0a=h5142b36_0
  - libssh2=1.8.2=ha12b0ac_0
  - libtiff=4.1.0=hcb84e12_0
  - libxml2=2.9.9=hf6e021a_1
  - lz4-c=1.8.1.2=h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.17.4=py37h890c691_0
  - numpy-base=1.17.4=py37h6575580_0
  - openjpeg=2.3.0=hb95cd4c_1
  - openssl=1.1.1d=h1de35cc_3
  - pcre=8.43=h0a44026_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h1de35cc_0
  - poppler=0.65.0=ha097c24_1
  - poppler-data=0.4.9=0
  - postgresql=11.2=h051b688_0
  - proj=6.2.1=hfd5b9e3_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.1.0=py37_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h359304d_1
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py37_1
  - setuptools=44.0.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=ha441bb4_0
  - tbb=2018.0.5=h04f5b5a_0
  - tiledb=1.6.3=h29f752d_0
  - tk=8.6.8=ha441bb4_0
  - urllib3=1.25.7=py37_0
  - wheel=0.33.6=py37_0
  - xerces-c=3.2.2=h44e365a_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
pip:
    - click==7.0
    - planet==1.4.4
    - requests-futures==0.9.7

